version: "3.9"
services:
  plutotv-scraper:
    profiles:
      - iptv
    build:
      context: ./iptv
      dockerfile: PlutoTV.Dockerfile
    container_name: plutotv-scraper
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/iptv:/data/iptv
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
  samsung-tv:
    profiles:
      - iptv
    image: matthuisman/samsung-tvplus-for-channels
    ports:
      - 8182:80
    container_name: samsung-tv
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/iptv:/data/iptv
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
  threadfin:
    profiles:
      - iptv
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./threadfin:/home/threadfin/conf
      - ${DATA_ROOT}/iptv:/data/iptv
    image: fyb3roptik/threadfin
    healthcheck:
      test: curl -fSs http://127.0.0.1:34400 || exit 1
      start_period: 180s
      timeout: 10s
      interval: 10s
      retries: 3
    restart: unless-stopped


