version: '3.9'

services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    ports:
      - "8265:8265" # WebUI
      - "8266:8266" # Server
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=MediaServer
    volumes:
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - ./tdarr/logs:/app/logs
      - ${DATA_ROOT}:/data
      - ${DOWNLOAD_ROOT}:/data/torrents
      - ${TRANSCODE_ROOT}:/temp
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=(Host(`${DOMAIN_NAME}`) && PathPrefix(`/tdarr`))
      - traefik.http.routers.tdarr.tls=true
      - traefik.http.routers.tdarr.tls.certresolver=myresolver
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
      - homepage.group=Media
      - homepage.name=TDarr
      - homepage.icon=tdarr.png
      - homepage.href=/tdarr
      - homepage.description=Bulk transcoder
      - homepage.weight=5
      - homepage.widget.type=tdarr
      - homepage.widget.url=http://tdarr:8265
    devices:
      - /dev/dri:/dev/dri
    profiles:
      - tdarr-server

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr
    ports:
      - "8265:8265" # WebUI
      - "8266:8266" # Server
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=002
      - serverIP=${TDARR_SERVER_IP}
      - serverPort=8266
      - inContainer=true
      - nodeName=TdarrNode
    volumes:
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - ./tdarr/logs:/app/logs
      - ./tdarr/transcode_cache:/temp
    labels:
      - homepage.group=Media
      - homepage.name=TDarr
      - homepage.icon=tdarr.png
      - homepage.href=/tdarr
    # devices:
    #   - /dev/dri:/dev/dri
    profiles:
      - tdarr-node